name: Build and Save DIA-NN Docker Image

on:
  workflow_dispatch:

jobs:
  save-tar:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/rmateosr/diann:2.0.2

      - name: Save Docker image as .tar
        run: |
          docker save -o diann-2.0.2.tar ghcr.io/rmateosr/diann:2.0.2

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: diann-2.0.2-tar
          path: diann-2.0.2.tar
