name: Build and Save DIA-NN Apptainer Image

on:
  workflow_dispatch:

jobs:
  save-sif:
    runs-on: ubuntu-latest

    steps:
      - name: Install Apptainer
        run: |
          sudo apt update
          sudo apt install -y squashfs-tools
          wget https://github.com/apptainer/apptainer/releases/download/v1.2.4/apptainer_1.2.4_amd64.deb
          sudo dpkg -i apptainer_1.2.4_amd64.deb

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/rmateosr/diann:2.0.2

      - name: Save Docker image as .tar
        run: |
          docker save -o diann-2.0.2.tar ghcr.io/rmateosr/diann:2.0.2

      - name: Convert `.tar` to Apptainer `.sif`
        run: |
          apptainer build diann-2.0.2.sif docker-archive://diann-2.0.2.tar

      - name: Upload Apptainer image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: diann-2.0.2-sif
          path: diann-2.0.2.sif
